CRIATURAS = "criaturas.csv"
MAGIZOOLOGOS = "magizoologos.csv"

DOCENCIO = "Docencio"
RESPONSABILIDAD_DOCENCIO = (15, 20)
MAGIA_DOCENCIO = (40, 60)
DESTREZA_DOCENCIO = (30, 40)
ENERGIA_DOCENCIO = (40, 50)
EXTRA_ALIMENTAR = 5
EXTRA_RECUPERAR = 7

TAREO = "Tareo"
RESPONSABILIDAD_TAREO = (10, 25)
MAGIA_TAREO = (40, 55)
DESTREZA_TAREO = (40, 50)
ENERGIA_TAREO = (35, 45)
PROB_SANAR = 70
PROB_RECUPERADO_ESPECIAL = 70

HIBRIDO = "Hibrido"
RESPONSABILIDAD_HIBRIDO = (10, 25)
MAGIA_HIBRIDO = (40, 55)
DESTREZA_HIBRIDO = (40, 50)
ENERGIA_HIBRIDO = (35, 45)
EXTRA_ALIMENTAR_HIBRIDO = 10

INOFENSIVA = "inofensiva"
EFECTO_INOFENSIVA = 0

ARISCA = "arisca"
EFECTO_ARISCA = 20

PELIGROSA = "peligrosa"
EFECTO_PELIGROSA = 40

SATISFECHA = "satisfecha"
EFECTO_SATISFECHA = 0

HAMBRIENTA = "hambrienta"
EFECTO_HAMBRIENTA = 15
EFECTO_HAMBRE = 20

AUGUREY = "Augurey"
PROB_ESCAPE_AUGUREY = 0.2
MAX_DIAS_SIN_COMER_AUGUREY = 3
PROB_ENFERMARSE_AUGUREY = 0.3
MAGIA_AUGUREY = (20, 25)
SALUD_AUGUREY = (35, 45)
PRECIO_AUGUREY = 75

NIFFLER = "Niffler"
PROB_ESCAPE_NIFFLER = 0.3
MAX_DIAS_SIN_COMER_NIFFLER = 2
PROB_ENFERMARSE_NIFFLER = 0.2
MAGIA_NIFFLER = (10, 20)
SALUD_NIFFLER = (20, 30)
CLEPTOMANIA_NIFFLER = (5, 10)
PRECIO_NIFFLER = 100

ERKLING = "Erkling"
PROB_ESCAPE_ERKLING = 0.5
MAX_DIAS_SIN_COMER_ERKLING = 2
PROB_ENFERMARSE_ERKLING = 0.3
MAGIA_ERKLING = (30, 45)
SALUD_ERKLING = (50, 60)
PRECIO_ERKLING = 125

DCC = "DCC"
MINIMO_APROBACION = 60
SICKLES_INICIALES = 500
COBRO_ENFERMAS = 70
PROB_ENFERMAS = 50
COBRO_ESCAPADAS = 50
PROB_ESCAPADAS = 70
COSTO_ALIMENTAR = 5
COBRO_VIDA_MINIMA = 150
COBRO_SANAR = 8
COSTO_RECUPERAR = 10

MALEZA = "Tarta de Melaza"
SALUD_MALEZA = 15
PRECIO_MALEZA = 10
ANTI_AGRESIVO = 15

DRAGON = "Hígado de Dragón"
PRECIO_DRAGON = 15
SALUD_DRAGON = 10

GUSARAJO = "Buñuelo de Gusarajo"
SALUD_GUSARAJO = 5
PRECIO_GUSARAJO = 3
RECHAZO = 65

PERDIDA_HAMBRE = 3
PERDIDA_ENFERMO = 7




